/*
 * MERC^T: Multiple External Representations of Computation Tutor
 * 
 *  (C) Richard Blumenthal, All rights reserved
 * 
 *  Unauthorized use, duplication or distribution without the authors'
 *  permission is strictly prohibited.
 * 
 *  Unless required by applicable law or agreed to in writing, this
 *  software is distributed on an "AS IS" basis without warranties
 *  or conditions of any kind, either expressed or implied.
 */
package edu.regis.merc.model;

import java.io.Serializable;

/**
 * A domain model with a unique id
 * 
 * @author rickb
 */
public abstract class Model implements Serializable {
    /**
     * A default identifier indicating a model that has not been saved to the DB. 
     */
    public static final int DEFAULT_ID = -1;
    
    /**
     * The unique id of this model (or the DEFAULT_ID if never assigned by the DB).
     */
    protected int id;
    
    /**
     * Instantiate this model with a DEFAULT_ID.
     */
    public Model() {
        this(DEFAULT_ID);
    }
    
    /**
     * Instantiate this model with the given id.
     * 
     * @param id the model's unique id, as determined by the database.
     */
    public Model(int id) {
        this.id = id;
    }

    /**
     * Return this model's id.
     * 
     * @return the unique id of this model assigned by the DB (or DEFAULT_ID) 
     */
    public int getId() {
        return id;
    }

    /**
     * Assign the unique id generated by the database to this model.
     * 
     * @param id the unique id generated by the database
     */
    public void setId(int id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Model other = (Model) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }
    
    @Override
    public String toString() {
        return "Model: " + id + ", " + super.toString();
    } 
}

