/*
 * MERC^T: Multiple External Representations of Computation Tutor
 * 
 *  (C) Richard Blumenthal, All rights reserved
 * 
 *  Unauthorized use, duplication or distribution without the authors'
 *  permission is strictly prohibited.
 * 
 *  Unless required by applicable law or agreed to in writing, this
 *  software is distributed on an "AS IS" basis without warranties
 *  or conditions of any kind, either expressed or implied.
 */
package edu.regis.merc.dao;

import edu.regis.merc.err.IllegalArgException;
import edu.regis.merc.err.InconsistentDBException;
import edu.regis.merc.err.NonRecoverableException;
import edu.regis.merc.err.ObjNotFoundException;
import edu.regis.merc.model.*;
import edu.regis.merc.svc.CourseSvc;
import edu.regis.merc.svc.ServiceFactory;
import edu.regis.merc.svc.SessionSvc;
import java.sql.*;
import java.util.*;

/**
 *
 * A Data Access Object implementing tutoring {@link SessionSvc} behaviors.
 * 
 * @author rickb
 */
public class SessionDAO extends MySqlDAO implements SessionSvc {

    public SessionDAO() {
        super();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void create(TutoringSession session) throws IllegalArgException, NonRecoverableException {
        // Align with schema: tutoring_sessions(userId, courseId, unitId, authToken, isActive, startedAt)
        final String sql = "INSERT INTO tutoring_sessions (userId, authToken, isActive, startedAt, courseId, unitId) VALUES (?,?,?,?,?,?)";

        Connection conn = null;
        PreparedStatement stmt = null;

        Account account = session.getStudent().getAccount();
        String userId = account.getUserId();

        try {
            conn = DriverManager.getConnection(URL);

            if (exists(userId, conn))
                throw new IllegalArgException("Tutoring session exists " + userId);

            stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            stmt.setString(1, userId);
            stmt.setString(2, session.getSecurityToken());
            stmt.setBoolean(3, session.isActive());
            stmt.setTimestamp(4, new Timestamp(session.getStartDate().getTimeInMillis()));
            stmt.setInt(5, session.getCourse().getId());
            stmt.setInt(6, session.getUnit().getId()); // Use the actual unit ID from session

            stmt.executeUpdate();

            // Get the id/key autogenerated by the DB
            ResultSet rs = stmt.getGeneratedKeys();
            if (rs.next()) {
                session.setId(rs.getInt(1));
                // Persist initial pending step for each pending task's current step
                createPendingSessionSteps(session, conn);
            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-1", e);

        } finally {
            close(conn, stmt);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TutoringSession retrieve(String userId) throws ObjNotFoundException, NonRecoverableException {
        // Align with schema: tutoring_sessions(sessionId, userId, authToken, isActive, startedAt, courseId, unitId)
        final String sql = "SELECT sessionId, authToken, isActive, startedAt, courseId, unitId FROM tutoring_sessions WHERE userId = ?";

        Connection conn = null;
        PreparedStatement stmt = null;

        try {
            conn = DriverManager.getConnection(URL);
            stmt = conn.prepareStatement(sql);

            stmt.setString(1, userId);

            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                // Only retrieve account and create student if session exists
                AccountDAO accDao = new AccountDAO();
                Account acc = accDao.retrieve(userId);
                Student stu = new Student(acc);
                TutoringSession session = new TutoringSession(stu);
                session.setId(rs.getInt(1));
                session.setSecurityToken(rs.getString(2));
                session.setIsActive(rs.getBoolean(3));

                Timestamp timestamp = rs.getTimestamp(4);
                GregorianCalendar calendar = new GregorianCalendar();
                calendar.setTimeInMillis(timestamp.getTime());
                session.setStartDate(calendar);

                int courseId = rs.getInt(5);
                int unitId = rs.getInt(6);

                CourseSvc courseSvc = ServiceFactory.findCourseSvc();
                try {
                    CourseDigest digest = courseSvc.retrieveDigest(courseId, conn);
                    session.setCourse(digest);
                } catch (ObjNotFoundException ex) {
                    String errMsg = "SessionDAO-ERR-2 Course digest not found for courseId " + courseId;
                    throw new NonRecoverableException(errMsg);
                }

                try {
                    UnitDigest unitDigest = courseSvc.retrieveUnitDigest(courseId, unitId, conn);
                    session.setUnit(unitDigest);

                } catch (ObjNotFoundException ex) {
                    String errMsg = "SessionDAO-ERR-3 Unit " + unitId + " not found in course " + courseId;
                    throw new NonRecoverableException(errMsg);
                }

                // Replace legacy retrievePendingTasks with new pending steps retrieval
                session.setTasks(retrievePendingTasksViaPendingSteps(session, conn));

                return session;

            } else {
                throw new ObjNotFoundException("Session not found for userId:" + userId);
            }
        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-4" + e.toString(), e);
        } finally {
            close(conn, stmt);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String retrieveSecurityToken(String userId) throws ObjNotFoundException, NonRecoverableException {
        final String sql = "SELECT authToken FROM tutoring_sessions WHERE userId = ?";

        Connection conn = null;
        PreparedStatement stmt = null;

        try {
            conn = DriverManager.getConnection(URL);
            stmt = conn.prepareStatement(sql);

            stmt.setString(1, userId);

            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                return rs.getString(1);

            } else {
                throw new ObjNotFoundException("User Id:" + userId);
            }
        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-5" + e.toString(), e);
        } finally {
            close(conn, stmt);
        }
    }

    /**
     * {@inheritDoc}
     * 
     * 1. Rename existing session file
     * 2. Create a new session file using the given update
     * 3. Delete the original, but now renamed file.
     */
    @Override
    public void update(TutoringSession session) throws ObjNotFoundException, NonRecoverableException {
        // Original behavior inserts a new row; align table/columns with schema
        final String sql = "INSERT INTO tutoring_sessions (userId, authToken, isActive, startedAt, courseId, unitId) VALUES (?,?,?,?,?,?)";

        Connection conn = null;
        PreparedStatement stmt = null;

        Account account = session.getStudent().getAccount();
        String userId = account.getUserId();

        try {
            conn = DriverManager.getConnection(URL);

            if (!exists(userId, conn))
                throw new ObjNotFoundException("No TutoringSession matching " + userId + " found.");

            stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            stmt.setString(1, userId);
            stmt.setString(2, session.getSecurityToken());
            stmt.setBoolean(3, session.isActive());
            stmt.setTimestamp(4, new Timestamp(session.getStartDate().getTimeInMillis()));
            stmt.setInt(5, session.getCourse().getId());
            stmt.setInt(6, session.getUnit().getId()); // Use the actual unit ID from session

            stmt.executeUpdate();

            // Get the id/key autogenerated by the DB
            ResultSet rs = stmt.getGeneratedKeys();
            if (rs.next()) {
                session.setId(rs.getInt(1));
                createPendingSessionSteps(session, conn);
            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-1", e);

        } finally {
            close(conn, stmt);
        }
    }
    
       /**
     * {@inheritDoc}
     */
    @Override
    public void delete(String userId) throws NonRecoverableException {
        final String sql = "DELETE FROM tutoring_sessions WHERE userId = ?";

        Connection conn = null;
        PreparedStatement stmt = null;

        try {
            conn = DriverManager.getConnection(URL);
            conn.setAutoCommit(false);
            stmt = conn.prepareStatement(sql);
            stmt.setString(1, userId);

            int rows = stmt.executeUpdate();

            if (rows != 1) {
                conn.rollback();
                throw new NonRecoverableException("Session delete deleted too many rows: " + rows);
            }

            conn.commit();
        } catch(SQLException e) {
            throw new NonRecoverableException("Delete Session Error", e);
        } finally {
            close(conn, stmt);
        }
    }

    // Persist current steps into pending_session_steps table (max 1 row per session)
    private void createPendingSessionSteps(TutoringSession session, Connection conn) throws NonRecoverableException {
        final String sql = "INSERT INTO pending_session_steps (sessionId, stepId, notifyTutor, isCompleted, currentHintIndex, studentState) VALUES (?,?,?,?,?,?)";
        PreparedStatement stmt = null;
        try {
            stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            int sessionId = session.getId();
            for (PendingTask pTask : session.getTasks()) {
                PendingStep pStep = pTask.currentStep();
                if (pStep == null) continue; // safety
                stmt.setInt(1, sessionId);
                stmt.setInt(2, pStep.getStep().getId());
                stmt.setBoolean(3, pStep.isNotifyTutor());
                stmt.setBoolean(4, pStep.isCompleted());
                stmt.setInt(5, pStep.getCurrentHintIndex());
                stmt.setString(6, pStep.getCurrentState());
                stmt.executeUpdate();
                ResultSet rs = stmt.getGeneratedKeys();
                if (rs.next()) {
                    pStep.setId(rs.getInt(1));
                }
                break; // only one active pending step per session per schema
            }
        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-PSS-1", e);
        } finally {
            close(stmt);
        }
    }

    // Retrieve pending steps and reconstruct PendingTasks
    private ArrayList<PendingTask> retrievePendingTasksViaPendingSteps(TutoringSession session, Connection conn) throws NonRecoverableException {
        final String sql = "SELECT pendingStepId, stepId, notifyTutor, isCompleted, currentHintIndex, studentState FROM pending_session_steps WHERE sessionId = ?";
        PreparedStatement stmt = null;
        ArrayList<PendingTask> tasks = new ArrayList<>();
        try {
            stmt = conn.prepareStatement(sql);
            stmt.setInt(1, session.getId());
            ResultSet rs = stmt.executeQuery();
            CourseSvc courseSvc = ServiceFactory.findCourseSvc();
            while (rs.next()) {
                int pendingStepId = rs.getInt(1);
                int stepId = rs.getInt(2);
                // Find task & step via courseSvc; assumes stepId uniquely identifies step within course tasks
                Task task = courseSvc.findTaskByStepId(session.getCourse().getId(), stepId, conn); // TODO: implement in CourseSvc if missing
                Step step = task.findStepById(stepId);
                PendingTask pTask = new PendingTask(task);
                PendingStep pStep = new PendingStep(step);
                pStep.setId(pendingStepId);
                pStep.setNotifyTutor(rs.getBoolean(3));
                pStep.setIsCompleted(rs.getBoolean(4));
                pStep.setCurrentHintIndex(rs.getInt(5));
                pStep.setCurrentState(rs.getString(6));
                pTask.setCurrentStep(pStep);
                tasks.add(pTask);
            }
            return tasks;
        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-PSS-2", e);
        } catch (ObjNotFoundException e) {
            throw new NonRecoverableException("SessionDAO-ERR-PSS-3", e);
        } finally {
            close(stmt);
        }
    }

    /**
     * @param sessionId the session id
     * @param conn an existing connection to the database
     * @return true, if the session exists, otherwise false
     * @throws NonRecoverableException (see ex.getCause().getErrorCode())
     */
    private boolean exists(int sessionId, Connection conn) throws NonRecoverableException {
        final String sql = "SELECT sessionId FROM tutoring_sessions WHERE sessionId = ?;";

        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);
            stmt.setInt(1, sessionId);

            ResultSet rs = stmt.executeQuery();

            return rs.next();
        } catch (SQLException e) {
            throw new NonRecoverableException("Exists Session Error", e);
        } finally {
            close(stmt);
        }
    }
    
        /**
     * @param userId the id of the user whose session is being checked
     * @param conn an existing connection to the database
     * @return true, if the session exists, otherwise false
     * @throws NonRecoverableException (see ex.getCause().getErrorCode())
     */
    private boolean exists(String userId, Connection conn) throws NonRecoverableException {
        final String sql = "SELECT sessionId FROM tutoring_sessions WHERE userId = ?;";

        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);
            stmt.setString(1, userId);

            ResultSet rs = stmt.executeQuery();

            return rs.next();
        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO.exists", e);
        } finally {
            close(stmt);
        }
    }
    
}

