/*
 * MERC^T: Multiple External Representations of Computation Tutor
 * 
 *  (C) Richard Blumenthal, All rights reserved
 * 
 *  Unauthorized use, duplication or distribution without the authors'
 *  permission is strictly prohibited.
 * 
 *  Unless required by applicable law or agreed to in writing, this
 *  software is distributed on an "AS IS" basis without warranties
 *  or conditions of any kind, either expressed or implied.
 */
package edu.regis.merc.dao;

import edu.regis.merc.err.IllegalArgException;
import edu.regis.merc.err.InconsistentDBException;
import edu.regis.merc.err.NonRecoverableException;
import edu.regis.merc.err.ObjNotFoundException;
import edu.regis.merc.model.Model;
import edu.regis.merc.model.Account;
import edu.regis.merc.model.CourseDigest;
import edu.regis.merc.model.PendingStep;
import edu.regis.merc.model.PendingTask;
import edu.regis.merc.model.Student;
import edu.regis.merc.model.Task;
import edu.regis.merc.model.TutoringSession;
import edu.regis.merc.model.UnitDigest;
import edu.regis.merc.svc.CourseSvc;
import edu.regis.merc.svc.ProblemSvc;
import edu.regis.merc.svc.ServiceFactory;
import edu.regis.merc.svc.SessionSvc;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * A Data Access Object implementing tutoring {@link SessionSvc} behaviors.
 *
 * @author rickb
 */
public class SessionDAO extends MySqlDAO implements SessionSvc {

    /**
     * MySqlDAO's logger is private, so this DAO needs its own.
     */
    private static final Logger LOGGER = Logger.getLogger(SessionDAO.class.getName());

    public SessionDAO() {
        super();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void create(TutoringSession session) throws IllegalArgException, NonRecoverableException {
        final String sql = "INSERT INTO TutoringSession (UserId, SecurityToken, IsActive, StartDate, CourseId, UnitId, ProblemId) VALUES (?,?,?,?,?,?,?)";

        Connection conn = null;
        PreparedStatement stmt = null;

        Account account = session.getStudent().getAccount();
        String userId = account.getUserId();

        try {
            conn = DriverManager.getConnection(URL);

            if (exists(userId, conn))
                throw new IllegalArgException("Tutoring session exists " + userId);

            stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            stmt.setString(1, userId);
            stmt.setString(2, session.getSecurityToken());
            stmt.setBoolean(3, session.isActive());
            stmt.setTimestamp(4, new Timestamp(session.getStartDate().getTimeInMillis()));
            stmt.setInt(5, session.getCourse().getId());
            stmt.setInt(6, 0); // Start with Unit 0
            stmt.setInt(7, session.getProblem().getId());

            stmt.executeUpdate();

            // Get the id/key autogenerated by the DB
            ResultSet rs = stmt.getGeneratedKeys();
            if (rs.next()) {
                session.setId(rs.getInt(1));

                createPendingTasks(session, conn);
            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-1", e);

        } finally {
            close(conn, stmt);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TutoringSession retrieve(String userId) throws ObjNotFoundException, NonRecoverableException {
        final String sql = "SELECT Id,SecurityToken,IsActive,StartDate,CourseId,UnitId,ProblemId FROM TutoringSession WHERE UserId = ?";

        Connection conn = null;
        PreparedStatement stmt = null;

        try {
            conn = DriverManager.getConnection(URL);
            stmt = conn.prepareStatement(sql);

            stmt.setString(1, userId);

            ResultSet rs = stmt.executeQuery();

            // I don't like this at all.
            // Just don't know how else to return a tutoring session when you need a
            // Student object to make a TutoringSession, but then in turn need an Account
            // object to make a student.
            // The account has the security token and the student the student model!
            AccountDAO accDao = new AccountDAO();
            Account acc = accDao.retrieve(userId);
            Student stu = new Student(acc);

            if (rs.next()) {
                TutoringSession session = new TutoringSession(stu);
                session.setId(rs.getInt(1));
                session.setSecurityToken(rs.getString(2));
                session.setIsActive(rs.getBoolean(3));

                Timestamp timestamp = rs.getTimestamp(4);
                GregorianCalendar calendar = new GregorianCalendar();
                calendar.setTimeInMillis(timestamp.getTime());
                session.setStartDate(calendar);

                int courseId = rs.getInt(5);
                int unitId = rs.getInt(6);

                CourseSvc courseSvc = ServiceFactory.findCourseSvc();
                try {
                    CourseDigest digest = courseSvc.retrieveDigest(courseId, conn);
                    session.setCourse(digest);
                } catch (ObjNotFoundException ex) {
                    String errMsg = "SessionDAO-ERR-2 Course digest not found for courseId " + courseId;
                    throw new NonRecoverableException(errMsg);
                }

                try {
                    UnitDigest unitDigest = courseSvc.retrieveUnitDigest(courseId, unitId, conn);
                    session.setUnit(unitDigest);

                } catch (ObjNotFoundException ex) {
                    String errMsg = "SessionDAO-ERR-3 Unit " + unitId + " not found in course " + courseId;
                    throw new NonRecoverableException(errMsg);
                }

                ProblemSvc problemSvc = ServiceFactory.findProbelmSvc();
                int problemId = rs.getInt("ProblemId");
                try {
                    session.setProblem(problemSvc.retrieve(problemId,conn));
                } catch (ObjNotFoundException ex) {
                    String errMsg = "SessionDAO-ERR-103 problem " + problemId + " not found in session for " + userId;
                    throw new NonRecoverableException(errMsg);
                }
                
                session.setTasks(retrievePendingTasks(session, conn));

                return session;

            } else {
                throw new ObjNotFoundException("Session not found for userId:" + userId);
            }
        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-4" + e.toString(), e);
        } finally {
            close(conn, stmt);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String retrieveSecurityToken(String userId) throws ObjNotFoundException, NonRecoverableException {
        final String sql = "SELECT SecurityToken FROM TutoringSession WHERE UserId = ?";

        Connection conn = null;
        PreparedStatement stmt = null;

        try {
            conn = DriverManager.getConnection(URL);
            stmt = conn.prepareStatement(sql);

            stmt.setString(1, userId);

            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                return rs.getString(1);

            } else {
                throw new ObjNotFoundException("User Id:" + userId);
            }
        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-5" + e.toString(), e);
        } finally {
            close(conn, stmt);
        }
    }

    /**
     * {@inheritDoc}
     * 
     * 1. Rename existing session file
     * 2. Create a new session file using the given update
     * 3. Delete the original, but now renamed file.
     */
    @Override
    public void update(TutoringSession session) throws ObjNotFoundException, NonRecoverableException {
        final String sql = "INSERT INTO TutoringSession (UserId, SecurityToken, IsActive, StartDate, CourseId, UnitId) VALUES (?,?,?,?,?,?)";

        Connection conn = null;
        PreparedStatement stmt = null;

        Account account = session.getStudent().getAccount();
        String userId = account.getUserId();

        try {
            conn = DriverManager.getConnection(URL);

            if (!exists(userId, conn))
                throw new ObjNotFoundException("No TutoringSession matching " + userId + " found.");

            stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            stmt.setString(1, userId);
            stmt.setString(2, session.getSecurityToken());
            stmt.setBoolean(3, session.isActive());
            stmt.setTimestamp(4, new Timestamp(session.getStartDate().getTimeInMillis()));
            stmt.setInt(5, session.getCourse().getId());
            stmt.setInt(6, 0); // Start with Unit 0

            stmt.executeUpdate();

            // Get the id/key autogenerated by the DB
            ResultSet rs = stmt.getGeneratedKeys();
            if (rs.next()) {
                session.setId(rs.getInt(1));

                createPendingTasks(session, conn);
            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-1", e);

        } finally {
            close(conn, stmt);
        }
    }
    
       /**
     * {@inheritDoc}
     */
    @Override
    public void delete(String userId) throws NonRecoverableException {
        final String sql = "DELETE FROM TutoringSession WHERE UserId = ?";

        Connection conn = null;
        PreparedStatement stmt = null;

        try {
            conn = DriverManager.getConnection(URL);
            conn.setAutoCommit(false);
            stmt = conn.prepareStatement(sql);
            stmt.setString(1, userId);

            int rows = stmt.executeUpdate();

            if (rows != 1) {
                conn.rollback();
                throw new NonRecoverableException("Session delete deleted too many rows: " + rows);
            }

            conn.commit();
        } catch(SQLException e) {
            throw new NonRecoverableException("Delete Session Error", e);
        } finally {
            close(conn, stmt);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void updateCurrentStep(TutoringSession session) throws NonRecoverableException {
        Connection conn = null;

        try {
            conn = DriverManager.getConnection(URL);

            // The writes below are a single logical change: a half-applied
            // advance would leave the session pointing at the old step with an
            // orphaned PendingStep row beside it.
            conn.setAutoCommit(false);

            int sessionId = session.getId();
            PendingTask pTask = session.currentTask();
            PendingStep pStep = pTask == null ? null : pTask.currentStep();

            if (pStep == null) {
                // Nothing to save, and continuing would raise an NPE inside the
                // transaction, which neither catch below would roll back.
                throw new NonRecoverableException(
                        "SessionDAO-ERR-21: Session " + sessionId + " has no current step to save");
            }

            if (pStep.getId() == Model.DEFAULT_ID) {
                // PendingTask.advanceStep() replaced the current step with a
                // new, unsaved one. Save the step it replaced, give the new one
                // a row of its own, and repoint the task at it.
                updatePendingStep(pTask.getReplacedStep(), conn);

                updatePendingTask(sessionId, createPendingStep(sessionId, pStep, conn), conn);

            } else {
                // Still on the same step; only its state changed.
                updatePendingStep(pStep, conn);
            }

            conn.commit();

        } catch (SQLException e) {
            rollback(conn);
            throw new NonRecoverableException("SessionDAO-ERR-19", e);

        } catch (NonRecoverableException e) {
            // The helpers signal a failed row count this way, not as SQLException.
            rollback(conn);
            throw e;

        } finally {
            close(conn);
        }
    }

    /**
     * Utility that deletes the given a file.
     *
     * @param file a File with an absolute path to delete.
     */
    private void delete(File file) {
        if (file.exists())
            file.delete();
    }

    /**
     * Roll back the given connection, logging rather than throwing on failure
     * so that a rollback error cannot mask the exception that caused it.
     *
     * @param conn the connection to roll back, which may be null
     */
    private void rollback(Connection conn) {
        if (conn != null) {
            try {
                conn.rollback();
            } catch (SQLException e) {
                LOGGER.log(Level.INFO, "SessionDAO-ERR-20: rollback() {0}", e.toString());
            }
        }
    }

    private void createPendingTasks(TutoringSession session, Connection conn)
            throws NonRecoverableException {
        final String sql = "INSERT INTO PendingTask (SessionId, TaskId, PendingStepId) VALUES (?,?,?)";

        int sessionId = session.getId();

        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);

            for (PendingTask pTask : session.getTasks()) {
                stmt.setInt(1, sessionId);
                stmt.setInt(2, pTask.getTask().getId());
                PendingStep pStep = pTask.currentStep();

                int pId = createPendingStep(sessionId, pStep, conn);
                stmt.setInt(3, pId);

                stmt.executeUpdate();

            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-7", e);

        } finally {
            close(stmt);
        }
    }

    /**
     * Point the given session's PendingTask at a different PendingStep, using
     * an established connection to the DB, which it does not close.
     *
     * This is how a student's progress through a task is recorded: the
     * PendingStep rows accumulate as history, and PendingTask names the one
     * they are currently on.
     *
     * SessionId alone is the PendingTask primary key, so a session has at most
     * one pending task and no TaskId is needed to identify the row.
     *
     * @param sessionId the id of the tutoring session whose task is moving
     * @param pendingStepId the id of an existing PendingStep row to point at
     * @param conn an open connection to the DB
     * @throws NonRecoverableException if the session has no PendingTask row,
     *         which leaves the update affecting no rows
     */
    private void updatePendingTask(int sessionId, int pendingStepId, Connection conn)
        throws NonRecoverableException {
        final String sql = "UPDATE PendingTask SET PendingStepId = ? WHERE SessionId = ?";

        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);

            stmt.setInt(1, pendingStepId);
            stmt.setInt(2, sessionId);

            int rows = stmt.executeUpdate();

            if (rows != 1) {
                throw new NonRecoverableException("SessionDAO-ERR-17: PendingTask Update Failed");
            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-18", e);

        } finally {
            close(stmt);
        }

    }

    private int createPendingStep(int sessionId, PendingStep pStep, Connection conn)
            throws NonRecoverableException {
        final String sql = "INSERT INTO PendingStep (SessionId, StepId, NotifyTutor, IsCompleted, CurrentHintIndex) VALUES (?,?,?,?,?)";

        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            stmt.setInt(1, sessionId);
            stmt.setInt(2, pStep.getStep().getId());
            stmt.setBoolean(3, pStep.isNotifyTutor());
            stmt.setBoolean(4, pStep.isCompleted());
            stmt.setInt(5, pStep.getCurrentHintIndex());

            stmt.executeUpdate();

            ResultSet rs = stmt.getGeneratedKeys();

            if (rs.next()) {
                int pId = rs.getInt(1);
                pStep.setId(pId);
                return pId;
            } else {
                throw new NonRecoverableException("SessionDAO-ERR-8: PendingStep AutoIncrement Failed");
            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-9", e);

        } finally {
            close(stmt);
        }
    }

    /**
     * Save the mutable state of an already persisted PendingStep, using an
     * established connection to the DB, which it does not close.
     *
     * Use this when the student's position within a step changes -- taking a
     * hint, or completing it -- rather than when they move to a new step. A
     * step they have moved on to has no row yet and belongs in
     * {@link #createPendingStep(int, PendingStep, Connection)} instead.
     *
     * The given PendingStep must carry the id of an existing row. An id of
     * {@link Model#DEFAULT_ID} means it was never saved, which is rejected
     * rather than allowed to update nothing silently.
     *
     * StepId is deliberately not updated: a row records progress on one
     * specific step for the life of that row, so moving to another step means
     * a new row rather than repointing this one.
     *
     * @param pStep a PendingStep whose id identifies the row to overwrite
     * @param conn an open connection to the DB
     * @throws NonRecoverableException if the step is null or was never
     *         persisted, or if its row no longer exists
     */
    private void updatePendingStep(PendingStep pStep, Connection conn)
        throws NonRecoverableException {

        final String sql = "UPDATE PendingStep SET NotifyTutor = ?, IsCompleted = ?, CurrentHintIndex = ? WHERE Id = ?";

        PreparedStatement stmt = null;

        try {
            if (pStep == null || pStep.getId() == Model.DEFAULT_ID) {
                throw new NonRecoverableException("SessionDAO-ERR-14: No PendingStep to Update");
            }
            stmt = conn.prepareStatement(sql);

            stmt.setBoolean(1, pStep.isNotifyTutor());
            stmt.setBoolean(2, pStep.isCompleted());
            stmt.setInt(3, pStep.getCurrentHintIndex());
            stmt.setInt(4, pStep.getId());

            int rows = stmt.executeUpdate();
            if (rows != 1) {
                throw new NonRecoverableException("SessionDAO-ERR-15: PendingStep Update Failed");
            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-16", e);

        } finally {
            close(stmt);
        }

    }

    private ArrayList<PendingTask> retrievePendingTasks(TutoringSession session, Connection conn)
            throws NonRecoverableException {

        final String sql = "SELECT TaskId, PendingStepId FROM PendingTask WHERE SessionId = ?";

        ArrayList<PendingTask> pendingTasks = new ArrayList<>();

        PreparedStatement stmt = null;

        int sessionId = session.getId();

        int taskId = -1;

        try {
            stmt = conn.prepareStatement(sql);

            stmt.setInt(1, sessionId);

            ResultSet rs = stmt.executeQuery();

           // CourseSvc courseSvc = ServiceFactory.findCourseSvc();

            while (rs.next()) {
                taskId = rs.getInt(1);
                
                // Task task = courseSvc.retrieveTask(session.getCourse().getId(), taskId, conn);
                Task task = session.getProblem().findTaskById(taskId);

                PendingTask pTask = new PendingTask(task);

                PendingStep pStep = retrievePendingStep(rs.getInt(2), sessionId, task, conn);

                pTask.setCurrentStep(pStep);

                pendingTasks.add(pTask);
            }

            return pendingTasks;

       // } catch (ObjNotFoundException ex) {
       //     String errMsg = "Task not found in pending task" + taskId;
         //   throw new NonRecoverableException("SessionDAO-ERR-10", new InconsistentDBException(errMsg));
        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-11", e);

        } finally {
            close(stmt);
        }
    }

    public PendingStep retrievePendingStep(int pendingStepId, int sessionId, Task task, Connection conn)
            throws NonRecoverableException {

        final String sql = "SELECT StepId, NotifyTutor, IsCompleted, CurrentHintIndex FROM PendingStep WHERE Id = ?";

        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);

            stmt.setInt(1, pendingStepId);

            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                PendingStep pStep = new PendingStep(task.findStepById(rs.getInt(1)));

                // Without the row's own id the loaded step looks unsaved, and
                // anything that later tries to update it has no row to target.
                pStep.setId(pendingStepId);

                pStep.setNotifyTutor(rs.getBoolean(2));
                pStep.setIsCompleted(rs.getBoolean(3));
                pStep.setCurrentHintIndex(rs.getInt(4));

                return pStep;
            } else {
                String errMsg = "PendingStep not found in pending task" + pendingStepId;
                throw new NonRecoverableException("SessionDAO-ERR-12", new InconsistentDBException(errMsg));
            }

        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO-ERR-13", e);

        } finally {
            close(stmt);
        }
    }

    /**
     * @param sessionId the session id
     * @param conn an existing connection to the database
     * @return true, if the session exists, otherwise false
     * @throws NonRecoverableException (see ex.getCause().getErrorCode())
     */
    private boolean exists(int sessionId, Connection conn) throws NonRecoverableException {
        final String sql = "SELECT SessionId FROM TutoringSession WHERE SessionId = ?;";
        
        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);
            stmt.setInt(1, sessionId);

            ResultSet rs = stmt.executeQuery();

            return rs.next();
        } catch (SQLException e) {
            throw new NonRecoverableException("Exists Session Error", e);
        } finally {
            close(stmt);
        }
    }
    
        /**
     * @param userId the id of the user whose session is being checked
     * @param conn an existing connection to the database
     * @return true, if the session exists, otherwise false
     * @throws NonRecoverableException (see ex.getCause().getErrorCode())
     */
    private boolean exists(String userId, Connection conn) throws NonRecoverableException {
        final String sql = "SELECT Id FROM TutoringSession WHERE UserId = ?;";
        
        PreparedStatement stmt = null;

        try {
            stmt = conn.prepareStatement(sql);
            stmt.setString(1, userId);

            ResultSet rs = stmt.executeQuery();

            return rs.next();
        } catch (SQLException e) {
            throw new NonRecoverableException("SessionDAO.exists", e);
        } finally {
            close(stmt);
        }
    }
    
}

